apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-template-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: express-template
          image: milantimotijevic89/express-template:0.8
          ports:
            - containerPort: 3000
          env:
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: DB_HOST
              value: postgres-cluster-ip-service
            - name: DB_PORT
              value: '5432'
            - name: DB_NAME
              value: local_db
