apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    component: postgres
spec:
  containers:
    - name: postgres
      image: postgres
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: local_db
